Repository Indipage/PPPiOS, pull requests merged in 2023-07, with the labels that each got.

#2 [Setting] #1 - GitHUB 세팅
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ Setting, 🐉 희재

#4 [Setting] #3 - 프로젝트 세팅
  .gitignore
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  PPPCLUB-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  PPPCLUB-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PPPCLUB-iOS.xcodeproj/xcuserdata/hellohidi.xcuserdatad/xcschemes/xcschememanagement.plist
  PPPCLUB-iOS/Application/AppDelegate.swift
  PPPCLUB-iOS/Application/SceneDelegate.swift
  PPPCLUB-iOS/Assets.xcassets/AccentColor.colorset/Contents.json
  PPPCLUB-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  PPPCLUB-iOS/Assets.xcassets/Contents.json
  PPPCLUB-iOS/Base.lproj/LaunchScreen.storyboard
  PPPCLUB-iOS/Base.lproj/Main.storyboard
  PPPCLUB-iOS/Data/Common/VoidResult.swift
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Global/Constant/URLs.swift
  PPPCLUB-iOS/Global/Extension/UIButton+.swift
  PPPCLUB-iOS/Global/Extension/UICollectionReusableView+.swift
  PPPCLUB-iOS/Global/Extension/UICollectionViewCell+.swift
  PPPCLUB-iOS/Global/Extension/UIColor+.swift
  PPPCLUB-iOS/Global/Extension/UIFont+.swift
  PPPCLUB-iOS/Global/Extension/UIImageView+.swift
  PPPCLUB-iOS/Global/Extension/UILabel+.swift
  PPPCLUB-iOS/Global/Extension/UITabbar+.swift
  PPPCLUB-iOS/Global/Extension/UITableViewCell+.swift
  PPPCLUB-iOS/Global/Extension/UITableViewHeaderFooterView+.swift
  PPPCLUB-iOS/Global/Extension/UITextField+.swift
  PPPCLUB-iOS/Global/Extension/UIView+.swift
  PPPCLUB-iOS/Global/Extension/UIViewController+.swift
  PPPCLUB-iOS/Info.plist
  PPPCLUB-iOS/Network/Foundation/APIConstants.swift
  PPPCLUB-iOS/Network/Foundation/BaseAPI.swift
  PPPCLUB-iOS/Network/Foundation/BaseTargetType.swift
  PPPCLUB-iOS/Network/Foundation/GenericResponse.swift
  PPPCLUB-iOS/Network/Foundation/MoyaLoggerPlugin.swift
  PPPCLUB-iOS/Network/Foundation/NetworkResult.swift
  PPPCLUB-iOS/Network/Foundation/SimpleResponse.swift
  PPPCLUB-iOS/ViewController.swift
Labels: ⚙️ Setting, 🐉 희재

#6 [Setting] #5 - 커스텀 TabBarController 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Application/SceneDelegate.swift
  PPPCLUB-iOS/Presentation/Base/BaseViewController.swift
  PPPCLUB-iOS/Presentation/Base/PPPTabBarController.swift
  PPPCLUB-iOS/Presentation/Bookmark/View/BookmarkView.swift
  PPPCLUB-iOS/Presentation/Bookmark/ViewController/BookmarkViewController.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PPPCLUB-iOS/Presentation/My/View/MyView.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MyViewController.swift
  PPPCLUB-iOS/Presentation/Search/View/SearchView.swift
  PPPCLUB-iOS/Presentation/Search/ViewController/SearchViewController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Contents.json
  PPPCLUB-iOS/Resource/Base.lproj/LaunchScreen.storyboard
  PPPCLUB-iOS/Resource/Base.lproj/Main.storyboard
Labels: ⚙️ Setting, 🐉 희재

#8 [Setting] #7 - 2차 프로젝트 세팅
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Extension/UIColor+.swift
  PPPCLUB-iOS/Global/Extension/UIFont+.swift
  PPPCLUB-iOS/Global/Extension/UIView+.swift
  PPPCLUB-iOS/Info.plist
  PPPCLUB-iOS/Presentation/Detail/View/DetailView.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
  PPPCLUB-iOS/Resource/Font/BioRhyme-Bold.ttf
  PPPCLUB-iOS/Resource/Font/BioRhyme-Light.ttf
  PPPCLUB-iOS/Resource/Font/BioRhyme-Regular.ttf
  PPPCLUB-iOS/Resource/Font/Pretendard-Light.otf
  PPPCLUB-iOS/Resource/Font/Pretendard-Medium.otf
  PPPCLUB-iOS/Resource/Font/Pretendard-SemiBold.otf
Labels: ⚙️ Setting, 🐉 희재

#12 [Feat] #9 - 티켓 QRCode 인식 기능 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Constant/Size.swift
  PPPCLUB-iOS/Global/Extension/CGPoint+.swift
  PPPCLUB-iOS/Global/Utility/QRManager.swift
  PPPCLUB-iOS/Presentation/Base/PPPTabBarController.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
Labels: ✨Feature, 🐉 희재

#21 [Feat] #19 - 마이페이지 UI 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/My/Model/MyAccountModel.swift
  PPPCLUB-iOS/Data/My/Model/MyInfoModel.swift
  PPPCLUB-iOS/Global/Extension/UIView+.swift
  PPPCLUB-iOS/Presentation/My/Cell/MyInfoTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySeparatorFooterView.swift
  PPPCLUB-iOS/Presentation/My/View/MyInfoView.swift
  PPPCLUB-iOS/Presentation/My/View/MyProfileView.swift
  PPPCLUB-iOS/Presentation/My/View/MySavedView.swift
  PPPCLUB-iOS/Presentation/My/View/MyView.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MyViewController.swift
Labels: ✨Feature, 🐉 희재

#20 [Feat] #16 - DetailUniqueView, DetailArticleRequestView, DetailMoveToArticleView UI 구현 완료
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Presentation/Detail/View/DetailArticleRequestView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailMoveToArticleView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailOwnerView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailUniqueView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailView.swift
Labels: ✨Feature, 🦖 윤빈

#26 [Setting] #24 - 프로젝트 세팅 및 탭바 수정
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Global/Extension/CALayer+.swift
  PPPCLUB-iOS/Global/Extension/UITabbar+.swift
  PPPCLUB-iOS/Presentation/Base/PPPTabBarController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.fill.imageset/Group 1171275618.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.fill.imageset/Group 1171275618@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.fill.imageset/Group 1171275618@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.imageset/Group 1171275618.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.imageset/Group 1171275618@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/article.imageset/Group 1171275618@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.fill.imageset/Group 1171275629.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.fill.imageset/Group 1171275629@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.fill.imageset/Group 1171275629@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.imageset/Group 1171275629.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.imageset/Group 1171275629@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/my.imageset/Group 1171275629@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.fill.imageset/Group 1171275619.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.fill.imageset/Group 1171275619@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.fill.imageset/Group 1171275619@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.imageset/Group 1171275619.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.imageset/Group 1171275619@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/search.imageset/Group 1171275619@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.fill.imageset/Group 1171275628.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.fill.imageset/Group 1171275628@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.fill.imageset/Group 1171275628@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.imageset/Group 1171275628.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.imageset/Group 1171275628@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/TabBar/ticket.imageset/Group 1171275628@3x.png
Labels: ⚙️ Setting, 🐉 희재

#31 [Feat] #28 - 마이페이지, 티켓 뷰 폰트, 컬러 적용
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Ticket/APIModel/TicketCardModel.swift
  PPPCLUB-iOS/Data/Ticket/APIModel/TicketModel.swift
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Global/Extension/CGFloat+.swift
  PPPCLUB-iOS/Global/Extension/UIFont+.swift
  PPPCLUB-iOS/Info.plist
  PPPCLUB-iOS/Presentation/Base/BaseViewController.swift
  PPPCLUB-iOS/Presentation/Base/PPPTabBarController.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailMoveToArticleView.swift
  PPPCLUB-iOS/Presentation/My/Cell/MyInfoTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySeparatorFooterView.swift
  PPPCLUB-iOS/Presentation/My/View/MyProfileView.swift
  PPPCLUB-iOS/Presentation/My/View/MySavedView.swift
  PPPCLUB-iOS/Presentation/My/View/MyView.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCardCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardEmptyView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketEmptyView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketFailureView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketSuccessView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketTicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketResultViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/mockTicket.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/mockTicket.imageset/Group 1171275564.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/mockTicket.imageset/Group 1171275564@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/mockTicket.imageset/Group 1171275564@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noCard.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noCard.imageset/Group 1171275632.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noCard.imageset/Group 1171275632@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noCard.imageset/Group 1171275632@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noTicket.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noTicket.imageset/Intersect.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noTicket.imageset/Intersect@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/noTicket.imageset/Intersect@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/forward.imageset/Frame 59812.png
  PPPCLUB-iOS/Resource/Assets.xcassets/forward.imageset/Frame 59812@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/forward.imageset/Frame 59812@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right@3x.png
Labels: ✨Feature, 🐉 희재

#35 [Feat] #32 - Ticket View 기능 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Utility/QRManager.swift
  PPPCLUB-iOS/Presentation/Base/PPPTabBarController.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardEmptyView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketEmptyView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketFailureView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketSuccessView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketTicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketFailureViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketSuccessViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
Labels: ✨Feature, 🐉 희재

#34 [Feat] #33 - SearchView 기능 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Search/APIModel/SearchListModel.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Presentation/Search/View/SearchView.swift
  PPPCLUB-iOS/Presentation/Search/ViewController/SearchViewController.swift
Labels: ✨Feature, 🦖 윤빈

#29 [Style] HomeArticleView UI 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Application/SceneDelegate.swift
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Presentation/Home/Cell/Dummy.swift
  PPPCLUB-iOS/Presentation/Home/Cell/HeaderFooterView/HomeArticleFooterView.swift
  PPPCLUB-iOS/Presentation/Home/Cell/HeaderFooterView/HomeArticleHeaderView.swift
  PPPCLUB-iOS/Presentation/Home/Cell/HomeArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleNavigationView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleTableView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeArticleViewController.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/articleTicket.imageset/Artboard 6 copy 3 사본 3@2x 1-2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleTicket.imageset/Artboard 6 copy 3 사본 3@2x 1-3.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleTicket.imageset/Artboard 6 copy 3 사본 3@2x 1.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleTicket.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/enterBookStore.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/enterBookStore.imageset/ios_articledetail_btn_tobookstoredetail-2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/enterBookStore.imageset/ios_articledetail_btn_tobookstoredetail-3.png
  PPPCLUB-iOS/Resource/Assets.xcassets/enterBookStore.imageset/ios_articledetail_btn_tobookstoredetail.png
Labels: ✨Feature, 🦕 지원

#41 [Feat] #37 - 티켓 애니메이션 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Ticket/APIModel/TicketCardModel.swift
  PPPCLUB-iOS/Global/Extension/UIView+.swift
  PPPCLUB-iOS/Global/Utility/QRManager.swift
  PPPCLUB-iOS/Presentation/Base/BaseButton.swift
  PPPCLUB-iOS/Presentation/My/View/MyProfileView.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCardCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketTicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketToggleView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketSuccessViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
Labels: ✨Feature, 🐉 희재

#44 [Style] #42 - 마이페이지 저장된 아티클, 서점 UI 구현
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleTableView.swift
  PPPCLUB-iOS/Presentation/My/Cell/MyInfoTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySavedArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySavedBookStoreTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/View/MyProfileView.swift
  PPPCLUB-iOS/Presentation/My/View/MySavedArticleView.swift
  PPPCLUB-iOS/Presentation/My/View/MySavedBookStoreView.swift
  PPPCLUB-iOS/Presentation/My/View/MySavedView.swift
  PPPCLUB-iOS/Presentation/My/View/MyView.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedArticleViewController.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedBookStoreViewController.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MyViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/My/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketNotReceivedImage.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketNotReceivedImage.imageset/Group 1171275643.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketNotReceivedImage.imageset/Group 1171275643@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketNotReceivedImage.imageset/Group 1171275643@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketReceivedImage.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketReceivedImage.imageset/Group 1171275605.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketReceivedImage.imageset/Group 1171275605@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/ticketReceivedImage.imageset/Group 1171275605@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/btn__.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/btn__@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/btn__@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Intersect.png
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Intersect@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Intersect@3x.png
Labels: ✨Feature, 🐉 희재

#45 [Style] - #36 DetailViewController UI 재구성
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Detail/APIModel/DetailModel.swift
  PPPCLUB-iOS/Data/Detail/APIModel/DetailTagModel.swift
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Global/Extension/UITextView+.swift
  PPPCLUB-iOS/Presentation/Component/PPPTagView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailArticleRequestView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailBookCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailMoveToArticleView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailOwnerView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailTagCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailTopView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailUniqueView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailView.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/gradient.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/gradient.imageset/Rectangle 40050.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/gradient.imageset/Rectangle 40051.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/gradient.imageset/Rectangle 40052.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/uniqueCard.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/uniqueCard.imageset/ios_bookstoredetail_speciality 1.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/uniqueCard.imageset/ios_bookstoredetail_speciality 2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Detail/uniqueCard.imageset/ios_bookstoredetail_speciality.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Mock/mockDetailCard.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Mock/mockDetailCard.imageset/Rectangle 40049.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Mock/mockDetailCard.imageset/Rectangle 40050.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Mock/mockDetailCard.imageset/Rectangle 40051.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__ 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__ 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default.svg
Labels: ✨Feature, 🔨 Fix, 🦖 윤빈

#47 [Setting] #46 - URL 및 이미지 세팅
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Constant/Config.swift
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Global/Constant/URLs.swift
  PPPCLUB-iOS/Info.plist
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankArticle.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankArticle.imageset/ios_graphic_articleblank.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankArticle.imageset/ios_graphic_articleblank@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankArticle.imageset/ios_graphic_articleblank@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankCard.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankCard.imageset/Group 1171275632.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankCard.imageset/Group 1171275632@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankCard.imageset/Group 1171275632@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankPlace.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankPlace.imageset/Group 1171275641.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankPlace.imageset/Group 1171275641@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankPlace.imageset/Group 1171275641@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankTicket.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankTicket.imageset/Intersect.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankTicket.imageset/Intersect@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Graphics/blankTicket.imageset/Intersect@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__ 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__ 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default.svg
Labels: ⚙️ Setting, 🐉 희재

#50 [Setting] #49 - 이미지 에셋 위치 변경
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/btn__.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/btn__@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.imageset/btn__@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__ 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__ 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/back.white.imageset/btn__.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/right.imageset/right@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.fill.imageset/Property 1=Fill.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default 1.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default 2.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/storeMark.imageset/Property 1=Default.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Intersect.png
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Intersect@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/ticket.imageset/Intersect@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/xmark.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/xmark.imageset/ic_x_btn.png
  PPPCLUB-iOS/Resource/Assets.xcassets/xmark.imageset/ic_x_btn@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/xmark.imageset/ic_x_btn@3x.png
Labels: ⚙️ Setting, 🐉 희재

#52 [Network] #51 - 마이페이지 API 서버통신
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/My/APIModel/MySavedArticleModel.swift
  PPPCLUB-iOS/Data/My/APIModel/MySavedSpaceModel.swift
  PPPCLUB-iOS/Data/My/APIModel/MyUserInfoModel.swift
  PPPCLUB-iOS/Global/Constant/Config.swift
  PPPCLUB-iOS/Network/Foundation/APIConstants.swift
  PPPCLUB-iOS/Network/Foundation/BaseAPI.swift
  PPPCLUB-iOS/Network/Foundation/BaseTargetType.swift
  PPPCLUB-iOS/Network/Foundation/GenericResponse.swift
  PPPCLUB-iOS/Network/Foundation/MoyaLoggerPlugin.swift
  PPPCLUB-iOS/Network/My/MyAPI.swift
  PPPCLUB-iOS/Network/My/MyService.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySavedArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/View/MyProfileView.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedArticleViewController.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedBookStoreViewController.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MyViewController.swift
  PPPCLUB-iOS/Presentation/Search/View/SearchTableViewCell.swift
Labels: ✨Feature, 🐉 희재

#56 [Style] #53 - HomeAllView UI 구현 & HomeWeeklyView 애니메이션 수정
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Constant/URLs.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeAllView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeNavigationView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklyView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeArticleViewController.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: ✨Feature, 🔨 Fix, 🦕 지원

#58 [Network] #53 - 티켓뷰 API 서버통신
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Common/VoidResult.swift
  PPPCLUB-iOS/Data/Ticket/APIModel/TicketCardModel.swift
  PPPCLUB-iOS/Data/Ticket/APIModel/TicketModel.swift
  PPPCLUB-iOS/Network/Foundation/BaseAPI.swift
  PPPCLUB-iOS/Network/Foundation/SimpleResponse.swift
  PPPCLUB-iOS/Network/Ticket/TicketAPI.swift
  PPPCLUB-iOS/Network/Ticket/TicketService.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCardCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
Labels: ✨Feature, 🐉 희재

#62 [Feat] #61 - DetailViewController 공간 북마크 관련 API 연동
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Detail/APIModel/DetailSavedBookMarkModel.swift
  PPPCLUB-iOS/Network/Detail/DetailAPI.swift
  PPPCLUB-iOS/Network/Detail/DetailService.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
Labels: ✨Feature, 🦖 윤빈

#65 [Refactor] #59 - 티켓뷰 코드 리펙토링
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Constant/Config.swift
  PPPCLUB-iOS/Global/Utility/QRManager.swift
  PPPCLUB-iOS/Network/Foundation/BaseTargetType.swift
  PPPCLUB-iOS/Network/Ticket/TicketAPI.swift
  PPPCLUB-iOS/Network/Ticket/TicketService.swift
  PPPCLUB-iOS/Presentation/Base/BaseViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardEmptyView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketEmptyView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketFailureView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketResultView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketSuccessView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketTicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketToggleView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketFailureViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketSuccessViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
Labels: ⚒️ Refactor, 🐉 희재

#72 [Refactor] - #71 DetailViewController 오류 해결
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Extension/UIImage+.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailBookCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailOwnerView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailView.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
Labels: ⚒️ Refactor, 🦖 윤빈

#73 [Fix] #67 - 아티클 상세페이지 동적으로 높이 조절 구현하기
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Extension/UILabel+.swift
  PPPCLUB-iOS/Presentation/Home/HomeArticleDummy.swift
  PPPCLUB-iOS/Presentation/Home/HomeCell/HomeArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleCollectionView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeArticleViewController.swift
Labels: 🔨 Fix, 🐉 희재

#81 [Fix] #80 - HomeView Ticket 여부에 따른 hidden 처리 코드 수정
  PPPCLUB-iOS/Presentation/Home/HomeHeaderFooterView/HomeArticleFooterView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklyView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🔨 Fix, 🦕 지원

#84 [Fix] #82 - 전반적인 오류 수정
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleNavigationView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySavedArticleTableViewCell.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/articleClickGO.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/articleClickGO.imageset/aos_articledetail_btn_tobookstoredetail-2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleClickGO.imageset/aos_articledetail_btn_tobookstoredetail-3.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleClickGO.imageset/aos_articledetail_btn_tobookstoredetail.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleClickGO.imageset/ios_articledetail_btn_tobookstoredetail-5.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleClickGO.imageset/ios_articledetail_btn_tobookstoredetail-6.png
  PPPCLUB-iOS/Resource/Assets.xcassets/articleClickGO.imageset/ios_articledetail_btn_tobookstoredetail.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Fill@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Variant2-2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Variant2-3.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.fill.imageset/Property 1=Variant2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default-2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default-3.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default.svg
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/bookMark.imageset/Property 1=Default@3x.png
Labels: 🔨 Fix, 🦕 지원

#86 [Fix] #76 - 아티클 뷰 오류 해결
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Extension/UILabel+.swift
  PPPCLUB-iOS/Global/Utility/ArticleParsingManager.swift
  PPPCLUB-iOS/Presentation/Home/HomeArticleDummy.swift
  PPPCLUB-iOS/Presentation/Home/HomeCell/HomeArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/Home/HomeHeaderFooterView/HomeArticleHeaderView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeArticleViewController.swift
Labels: 🔨 Fix, 🐉 희재

#88 [Feat] - #83 Search View API 연동
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Search/APIModel/SearchSpaceModel.swift
  PPPCLUB-iOS/Global/Constant/URLs.swift
  PPPCLUB-iOS/Network/Search/SearchAPI.swift
  PPPCLUB-iOS/Network/Search/SearchService.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Presentation/Search/View/SearchTableViewCell.swift
  PPPCLUB-iOS/Presentation/Search/View/SearchView.swift
  PPPCLUB-iOS/Presentation/Search/ViewController/SearchViewController.swift
Labels: ✨Feature, 🦖 윤빈

#89 [Network] #87 - 아티클 상세조회 API 서버통신
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Data/Home/APIModel/HomeDetailArticleResult.swift
  PPPCLUB-iOS/Network/Home/HomeAPI.swift
  PPPCLUB-iOS/Network/Home/HomeService.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Presentation/Home/HomeArticleDummy.swift
  PPPCLUB-iOS/Presentation/Home/HomeCell/HomeArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/Home/HomeHeaderFooterView/HomeArticleHeaderView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleCollectionView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeArticleViewController.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySavedArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedArticleViewController.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedBookStoreViewController.swift
Labels: ✨Feature, 🐉 희재

#93 [Refactor]#90 - 전체적인 코드 리팩토링
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Application/SceneDelegate.swift
  PPPCLUB-iOS/Data/My/APIModel/MySavedSpaceModel.swift
  PPPCLUB-iOS/Data/My/APIModel/MyUserInfoModel.swift
  PPPCLUB-iOS/Data/Search/APIModel/SearchListModel.swift
  PPPCLUB-iOS/Data/Ticket/APIModel/TicketQRCodeModel.swift
  PPPCLUB-iOS/Global/Utility/AnimationManager.swift
  PPPCLUB-iOS/Global/Utility/QRManager.swift
  PPPCLUB-iOS/Network/Ticket/TicketAPI.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Presentation/Home/HomeCell/HomeArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedBookStoreViewController.swift
  PPPCLUB-iOS/Presentation/Search/View/SearchTableViewCell.swift
  PPPCLUB-iOS/Presentation/Search/ViewController/SearchViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketSuccessView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketCheckQRCodeViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketFailureViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketSuccessViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
Labels: ⚒️ Refactor, 🐉 희재

#98 [Refactor] #94 - 전체적인 에러 수정 & 기능 추가
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Application/AppDelegate.swift
  PPPCLUB-iOS/Data/Home/APIModel/HomeTicketCheckModel.swift
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Global/Utility/AnimationManager.swift
  PPPCLUB-iOS/Global/Utility/ArticleParsingManager.swift
  PPPCLUB-iOS/Network/Home/HomeAPI.swift
  PPPCLUB-iOS/Network/Home/HomeService.swift
  PPPCLUB-iOS/Network/Ticket/TicketService.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Presentation/Home/HomeCell/HomeArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/Home/HomeHeaderFooterView/HomeArticleFooterView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeArticleNavigationView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklyView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeArticleViewController.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySavedArticleTableViewCell.swift
  PPPCLUB-iOS/Presentation/My/View/MySavedView.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MySavedBookStoreViewController.swift
  PPPCLUB-iOS/Presentation/My/ViewController/MyViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketFailureView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketSuccessView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketToggleView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/로고.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/로고@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/로고@3x 1.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedArticle.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedArticle.imageset/Rectangle 39948.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedArticle.imageset/Rectangle 39948@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedArticle.imageset/Rectangle 39948@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedSpace.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedSpace.imageset/Rectangle 39947.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedSpace.imageset/Rectangle 39947@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/savedSpace.imageset/Rectangle 39947@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/qrFail.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/qrFail.imageset/Rectangle 40049.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/qrFail.imageset/Rectangle 40049@2x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/Ticket/qrFail.imageset/Rectangle 40049@3x.png
  PPPCLUB-iOS/Resource/Assets.xcassets/pppIcon.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/pppIcon.imageset/로고-1.png
  PPPCLUB-iOS/Resource/Assets.xcassets/pppIcon.imageset/로고.png
  PPPCLUB-iOS/Resource/Assets.xcassets/pppIcon.imageset/로고@2x.png
  PPPCLUB-iOS/Resource/Base.lproj/LaunchScreen.storyboard
Labels: ⚒️ Refactor, 🐉 희재

#101 [Fix] #99 - HomeVIew 에러 수정
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Presentation/Home/HomeArticleParsing.swift
  PPPCLUB-iOS/Presentation/Home/HomeCell/WeeklyCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklySlideYetView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklySlidedView.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklyView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🔨 Fix, 🦕 지원

#102 [Fix] #100 - UI 수정사항 및 스와이프 모션
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Global/Constant/Image.swift
  PPPCLUB-iOS/Global/Extension/UIViewController+.swift
  PPPCLUB-iOS/Presentation/Base/BaseViewController.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailBookCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailMoveToArticleView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailTopView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailUniqueView.swift
  PPPCLUB-iOS/Presentation/Detail/View/DetailView.swift
  PPPCLUB-iOS/Presentation/Detail/ViewController/DetailViewController.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklyView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PPPCLUB-iOS/Presentation/My/View/MyProfileView.swift
  PPPCLUB-iOS/Presentation/Search/View/SearchTableViewCell.swift
  PPPCLUB-iOS/Presentation/Search/ViewController/SearchViewController.swift
  PPPCLUB-iOS/Presentation/Ticket/Cell/TicketCardCollectionViewCell.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketCardView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketFailureView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketSuccessView.swift
  PPPCLUB-iOS/Presentation/Ticket/View/TicketTicketView.swift
  PPPCLUB-iOS/Presentation/Ticket/ViewController/TicketViewController.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/My/profile.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/My/profile.imageset/Mask group 1.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/profile.imageset/Mask group 2.png
  PPPCLUB-iOS/Resource/Assets.xcassets/My/profile.imageset/Mask group.png
Labels: 🔨 Fix, 🦖 윤빈

#108 [Fix] #104 - 오류 수정
  PPPCLUB-iOS.xcodeproj/project.pbxproj
  PPPCLUB-iOS/Application/AppDelegate.swift
  PPPCLUB-iOS/Global/Extension/UILabel+.swift
  PPPCLUB-iOS/Global/Utility/ArticleParsingManager.swift
  PPPCLUB-iOS/Info.plist
  PPPCLUB-iOS/Presentation/Component/PPPToastMessage.swift
  PPPCLUB-iOS/Presentation/Home/View/HomeWeeklySlideYetView.swift
  PPPCLUB-iOS/Presentation/Home/ViewController/HomeArticleViewController.swift
  PPPCLUB-iOS/Presentation/My/Cell/MySavedBookStoreTableViewCell.swift
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  PPPCLUB-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/ppp.imageset/Contents.json
  PPPCLUB-iOS/Resource/Assets.xcassets/ppp.imageset/로고 1.png
  PPPCLUB-iOS/Resource/Assets.xcassets/ppp.imageset/로고-1.png
  PPPCLUB-iOS/Resource/Assets.xcassets/ppp.imageset/로고@2x.png
  PPPCLUB-iOS/Resource/Base.lproj/LaunchScreen.storyboard
  PPPCLUB-iOS/Resource/Base.lproj/Main.storyboard
  PPPCLUB-iOS/Resource/LaunchScreenAsset/logo.png
Labels: 🔨 Fix, 🐉 희재
